//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Autod_ja_Omanikud.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Autod_ja_Omanikud.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Car.
        /// </summary>
        internal static string btnAddCar {
            get {
                return ResourceManager.GetString("btnAddCar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Entry.
        /// </summary>
        internal static string btnAddCarService {
            get {
                return ResourceManager.GetString("btnAddCarService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Owner.
        /// </summary>
        internal static string btnAddOwner {
            get {
                return ResourceManager.GetString("btnAddOwner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        internal static string btnAddService {
            get {
                return ResourceManager.GetString("btnAddService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string btnDeleteCar {
            get {
                return ResourceManager.GetString("btnDeleteCar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string btnDeleteOwner {
            get {
                return ResourceManager.GetString("btnDeleteOwner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string btnDeleteService {
            get {
                return ResourceManager.GetString("btnDeleteService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        internal static string btnRefresh {
            get {
                return ResourceManager.GetString("btnRefresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark Mode.
        /// </summary>
        internal static string btnToggleDarkMode {
            get {
                return ResourceManager.GetString("btnToggleDarkMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        internal static string btnUpdateCar {
            get {
                return ResourceManager.GetString("btnUpdateCar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Entry.
        /// </summary>
        internal static string btnUpdateCarService {
            get {
                return ResourceManager.GetString("btnUpdateCarService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        internal static string btnUpdateOwner {
            get {
                return ResourceManager.GetString("btnUpdateOwner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        internal static string btnUpdateService {
            get {
                return ResourceManager.GetString("btnUpdateService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto Manager.
        /// </summary>
        internal static string Form1_Title {
            get {
                return ResourceManager.GetString("Form1_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cars.
        /// </summary>
        internal static string tabCars {
            get {
                return ResourceManager.GetString("tabCars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maintenance.
        /// </summary>
        internal static string tabMaintenance {
            get {
                return ResourceManager.GetString("tabMaintenance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Owners.
        /// </summary>
        internal static string tabOwners {
            get {
                return ResourceManager.GetString("tabOwners", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brand.
        /// </summary>
        internal static string txtCarBrand_Placeholder {
            get {
                return ResourceManager.GetString("txtCarBrand_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model.
        /// </summary>
        internal static string txtCarModel_Placeholder {
            get {
                return ResourceManager.GetString("txtCarModel_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration.
        /// </summary>
        internal static string txtCarReg_Placeholder {
            get {
                return ResourceManager.GetString("txtCarReg_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mileage.
        /// </summary>
        internal static string txtMileage_Placeholder {
            get {
                return ResourceManager.GetString("txtMileage_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Name.
        /// </summary>
        internal static string txtOwnerName_Placeholder {
            get {
                return ResourceManager.GetString("txtOwnerName_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        internal static string txtOwnerPhone_Placeholder {
            get {
                return ResourceManager.GetString("txtOwnerPhone_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Name.
        /// </summary>
        internal static string txtServiceName_Placeholder {
            get {
                return ResourceManager.GetString("txtServiceName_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price.
        /// </summary>
        internal static string txtServicePrice_Placeholder {
            get {
                return ResourceManager.GetString("txtServicePrice_Placeholder", resourceCulture);
            }
        }
    }
}
